### PR TITLE
[Gradle JDK Automanagement][Intellij plugin] Background tool window

### LINKED ISSUE #395: Intellij plugin: Can the popup not steal focus
## What happened?
When it runs, the window steals focus which can be quite jarring + the window opened is quite large.

## What did you want to happen?
Run in the background like the normal gradle import action and only steal focus when it fails.

See internal reproducer gif

### PR DESCRIPTION
**Pull request by crogoz**
## After this PR
Fixes: https://github.com/palantir/gradle-jdks/issues/395
- `Gradle JDK setup` tool window will be minimized by default
- The `Gradle JDK setup` would look as if it were a background process (similar to the `Gradle Sync` workflow)
- If the `Gradle JDK setup` fails, then we will show a pop-up Notification with a link to the logs. 

==COMMIT_MSG==
[Gradle JDK Automanagement][Intellij plugin] Background tool window
==COMMIT_MSG==

Note: I've tried using the declarative setup for the `Gradle JDK setup` toolWindow (https://plugins.jetbrains.com/docs/intellij/tool-windows.html#declarative-setup) but the workflow had 2 issues: 
-  some initial logs might be missing from the consoleView, I suspect this is because the [consoleView creation](https://github.com/palantir/gradle-jdks/blob/f529abb2eaa2e5ae1d477906036fabec49d51260/idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdkToolWindowFactory.java#L43) would happen after we started [running the gradle jdk setup](https://github.com/palantir/gradle-jdks/blob/f529abb2eaa2e5ae1d477906036fabec49d51260/idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java#L120C13-L120C29)

### CODE REVIEW

File: idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java [hunk 1]
```diff
@@ -90,7 +110,28 @@ public void maybeSetupGradleJdks() {
                     "Skipping setupGradleJdks because gradle JDK setup is not found %s", gradleSetupScript));
             return;
         }
-        setupGradleJdks();
+        TasksKt.withBackgroundProgress(
```
Comment (crogoz) [inline idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java:111]: instead of: https://github.com/JetBrains/intellij-community/blob/99964dd3c76f6cf9eb24018c002a68848e54dddb/platform/core-api/src/com/intellij/openapi/progress/Task.java#L43C8-L43C12 which has obsolescence notice

File: idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java [hunk 2]
```diff
@@ -90,7 +110,28 @@ public void maybeSetupGradleJdks() {
...
+                },
+                new Continuation<>() {
+                    @Override
+                    public @NotNull CoroutineContext getContext() {
+                        return EmptyCoroutineContext.INSTANCE;
+                    }
+
+                    @Override
+                    public void resumeWith(@NotNull Object _object) {}
+                });
```
Comment (crogoz) [inline idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java:132]: the Gradle JDK setup process would look similar to the Gradle Sync background process. The logs can be seen in `Gradle JDK Setup` window tab. 

Screenshot 2024-09-06 at 12 21 50 PM

File: idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java [hunk 3]
```diff
@@ -109,6 +151,21 @@ public void processTerminated(@NotNull ProcessEvent _event) {
             consoleView.get().attachToProcess(handler);
             ProcessTerminatedListener.attach(handler, project, "Gradle JDK setup finished with exit code $EXIT_CODE$");
             handler.waitFor();
+            if (handler.getExitCode() != 0) {
+                Notification notification = NotificationGroupManager.getInstance()
```
Comment (crogoz) [inline idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java:153]: if the process has failed for any reason, a pop-up will appear: 

Screenshot 2024-09-06 at 12 28 17 PM

I could also focus the `Gradle JDK setup` window tool by default. wdyt ?

File: idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java [hunk 4]
```diff
@@ -72,13 +83,22 @@ private ConsoleView initConsoleView() {
             ContentFactory contentFactory = ContentFactory.getInstance();
             Content content = contentFactory.createContent(newConsoleView.getComponent(), "", false);
             toolWindow.getContentManager().addContent(content);
-            // TODO(crogoz): Focus only when error or takes a long time?
-            toolWindow.activate(null);
+            Disposer.register(project, newConsoleView);
```
Comment (crogoz) [inline idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java:84]: maybe this fixes: https://github.com/palantir/gradle-jdks/issues/394 I wasn't able to repro the issue

File: idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java (hunk 3 above)
Comment (felixdesouza) [reply idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java:153]: I think it makes sense to focus the window on failure. The notification windows are quite quiet. I for some reason barely ever notice the "required plugins" notification lolol and I think it's quite common.

File: idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java (hunk 4 above)
Comment (felixdesouza) [reply idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java:84]: 🙏

File: idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java (hunk 3 above)
Comment (crogoz) [reply idea-plugin/src/main/java/com/palantir/gradle/jdks/GradleJdksProjectService.java:153]: addressed in: https://github.com/palantir/gradle-jdks/pull/405/commits/aceac47034cba90dacecf8fe3f41de79337b5331

**Review by CRogers — APPROVED** [review]
